# From https://www.robopenguins.com/cross-compiling/
FROM debian:bookworm
RUN apt-get update \
&& apt-get install -y \
build-essential \
wget \
git \
g++-arm-linux-gnueabihf \
g++-aarch64-linux-gnu \
&& rm -rf /var/lib/apt/lists/*